sonar.projectKey=cash_track
sonar.host.url=http://localhost:9000
sonar.token=sqp_a276d1669dcbbf0ba9aa5d34d022ec06251ff2ff

# Ajustar sonar.sources para excluir los archivos de prueba
sonar.sources=components,lib,pages,prisma,public,scripts,styles,types

# Mantener los archivos de prueba en sonar.tests
sonar.tests=__tests__

# Exclusiones para evitar duplicados y archivos innecesarios
sonar.exclusions=node_modules/**, coverage/**, dist/**, __tests__/**